#!/usr/bin/env sh
#
# Small script that autogenerates a mono project file given the
# project file name and the directory to generate the project in. By
# default, the mono project will be generated for the src and test
# directories.
#
# author: Manu Sporny

BASE_DIR=`pwd`
SOLUTION_NAME="Lazarus"
SOLUTION_FILE="$BASE_DIR/$SOLUTION_NAME.mds"

PROJECT_FILES=`find . -name "*.mdp"`

echo "
<Combine name=\"Lazarus\" fileversion=\"2.0\">
  <Configurations>
    <Configuration name=\"Debug\" ctype=\"CombineConfiguration\">" > $SOLUTION_FILE

for file in $PROJECT_FILES
do
   PROJECT=`basename $file .mdp`
   echo "      <Entry build=\"True\" name=\"$PROJECT\" />" >> $SOLUTION_FILE
done

echo "    </Configuration>
    <Configuration name=\"Release\" ctype=\"CombineConfiguration\">" >> $SOLUTION_FILE

for file in $PROJECT_FILES
do
   PROJECT=`basename $file .mdp`
   echo "      <Entry build=\"True\" name=\"$PROJECT\" />" >> $SOLUTION_FILE
done

echo "    </Configuration>
  </Configurations>
  <StartMode startupentry=\"Sms.Common\" single=\"True\">
    <Execute type=\"None\" entry=\"Sms.Common\" />
  </StartMode>
  <Entries>" >> $SOLUTION_FILE

for file in $PROJECT_FILES
do
   echo "      <Entry filename=\"$file\" />" >> $SOLUTION_FILE
done

echo "  </Entries>
</Combine>" >> $SOLUTION_FILE

echo "Created Monodevelop Solution: $SOLUTION_FILE"
